GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/5

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Irwin",
  "lastname": "Capitan",
  "email": "irwin.capitan@example.com",
  "password": "666666",
  "phone": "998813456",
  "dni": "88888888",
  "role": "user"
}